apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eventfund-backend-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm-store
    kind: ClusterSecretStore
  target:
    name: eventfund-backend-secret
    creationPolicy: Owner
  dataFrom:
    - find:
        path: /eventfund/PLACEHOLDER/backend  # MUST be overridden by overlay (dev or prod)
        name:
          regexp: ".*"
      rewrite:
        - regexp:
            source: "/eventfund/PLACEHOLDER/backend/(.*)"  # MUST be overridden by overlay
            target: "$1"
